###############################################################################
#                         docker-compose up --build -d                        #
###############################################################################

services:
  postgres:
    container_name: form-db
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '58002:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: form-admin
    image: dpage/pgadmin4
    ports:
      - "58003:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    restart: unless-stopped

  webserver:
    container_name: form-server
    image: 'nginx:alpine'
    working_dir: /application
    volumes:
      - './public:/application/public'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php-fpm2
    ports:
      - '58000:80'
    restart: unless-stopped

  php-fpm2:
    container_name: php-fpm2
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /application
    volumes:
      - .:/application
    depends_on:
      - postgres
    command: php-fpm -F
    restart: unless-stopped

volumes:
  postgres_data:
