###############################################################################
#                         docker-compose up --build -d                        #
###############################################################################

services:
  postgres:
    container_name: form-db
    image: postgres:16
    env_file:
      - /backend/.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '58002:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: form-admin
    image: dpage/pgadmin4
    ports:
      - "58003:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    restart: unless-stopped

  webserver:
    container_name: form-server
    image: 'nginx:alpine'
    working_dir: /application/backend
    volumes:
      - './backend/public:/application/backend/public'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php-fpm
    ports:
      - '58000:80'
    restart: unless-stopped

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /application/backend
    volumes:
      - ./backend:/application/backend
    depends_on:
      - postgres
    restart: unless-stopped
    command: php-fpm -F

volumes:
  postgres_data:
